export const dailyItems: { [key: string]: string } = {
    "2025-11-04": "a dolphin",
    "2025-11-05": "pizza",
    "2025-11-06": "Albert Einstein",
    "2025-11-07": "a banana",
    "2025-11-08": "Christmas",
    "2025-11-09": "Paris",
    "2025-11-10": "sushi",
    "2025-11-11": "Cinderella",
    "2025-11-12": "a mirror",
    "2025-11-13": "coffee",
    "2025-11-14": "a penguin",
    "2025-11-15": "chocolate",
    "2025-11-16": "a carrot",
    "2025-11-17": "a compass",
    "2025-11-18": "Halloween",
    "2025-11-19": "New York",
    "2025-11-20": "a hamburger",
    "2025-11-21": "Harry Potter",
    "2025-11-22": "lemonade",
    "2025-11-23": "a strawberry",
    "2025-11-24": "an elephant",
    "2025-11-25": "ice cream",
    "2025-11-26": "the Eiffel Tower",
    "2025-11-27": "a backpack",
    "2025-11-28": "swimming",
    "2025-11-29": "a shark",
    "2025-11-30": "pasta",
    "2025-12-01": "Mickey Mouse",
    "2025-12-02": "a camera",
    "2025-12-03": "cooking",
    "2025-12-04": "an apple",
    "2025-12-05": "a taco",
    "2025-12-06": "London",
    "2025-12-07": "orange juice",
    "2025-12-08": "gravity",
    "2025-12-09": "a parrot",
    "2025-12-10": "a sandwich",
    "2025-12-11": "Sherlock Holmes",
    "2025-12-12": "a flashlight",
    "2025-12-13": "a wedding",
    "2025-12-14": "a watermelon",
    "2025-12-15": "popcorn",
    "2025-12-16": "the Great Wall",
    "2025-12-17": "milk",
    "2025-12-18": "a sunrise",
    "2025-12-19": "broccoli",
    "2025-12-20": "a croissant",
    "2025-12-21": "Peter Pan",
    "2025-12-22": "candy",
    "2025-12-23": "hope",
    "2025-12-24": "a pineapple",
    "2025-12-25": "gingerbread",
    "2025-12-26": "Santa Claus",
    "2025-12-27": "Tokyo",
    "2025-12-28": "a dream",
    "2025-12-29": "gummy bears",
    "2025-12-30": "champagne",
    "2025-12-31": "fireworks",
    "2026-01-01": "a mango",
    "2026-01-02": "Pinocchio",
    "2026-01-03": "hot chocolate",
    "2026-01-04": "a tomato",
    "2026-01-05": "the Statue of Liberty",
    "2026-01-06": "a lollipop",
    "2026-01-07": "a lion",
    "2026-01-08": "Rome",
    "2026-01-09": "a cookie",
    "2026-01-10": "Aladdin",
    "2026-01-11": "tea",
    "2026-01-12": "a potato",
    "2026-01-13": "the Pyramids",
    "2026-01-14": "a cupcake",
    "2026-01-15": "a butterfly",
    "2026-01-16": "Sydney",
    "2026-01-17": "a grape",
    "2026-01-18": "Snow White",
    "2026-01-19": "soda",
    "2026-01-20": "a cucumber",
    "2026-01-21": "the Taj Mahal",
    "2026-01-22": "a donut",
    "2026-01-23": "a kangaroo",
    "2026-01-24": "Batman",
    "2026-01-25": "smoothie",
    "2026-01-26": "an onion",
    "2026-01-27": "Disney World",
    "2026-01-28": "a brownie",
    "2026-01-29": "a peacock",
    "2026-01-30": "Elsa"
};

export const DEFAULT_ITEM = "a key";

export const itemDetails: { [key: string]: { hints: string[] } } = {
    "a dolphin": { hints: ["An animal.", "You usually find it in oceans."] },
    "pizza": { hints: ["It is a food.", "It is round", "The word has 5 letters."] },
    "Albert Einstein": { hints: ["A famous person.", "This person won the Nobel Prize"] },
    "a banana": { hints: ["A fruit.", "It is usually yellow"] },
    "Christmas": { hints: ["You cannot touch it"] },
    "Paris": { hints: ["A place."] },
    "sushi": { hints: ["It is a food.", "Related to Japan"]},
    "Cinderella": { hints: ["A fictional character"] },
    "a mirror": { hints: ["You usually find it in bedrooms."] },
    "coffee": { hints: ["A liquid", "Related to the morning"] },
    "a penguin": { hints: ["A bird that cannot fly.", "It has black and white coloring."] },
    "chocolate": { hints: ["A food.", "It is usually black"] },
    "a carrot": { hints: ["A vegetable.", "It is orange"] },
    "a compass": { hints: ["A tool."] },
    "Halloween": { hints: ["A day."] },
    "New York": { hints: ["A place."] },
    "a hamburger": { hints: ["A food."] },
    "Harry Potter": { hints: ["A fictional character.", "Related to lightning."] },
    "lemonade": { hints: ["A beverage.", "It is sour."] },
    "a strawberry": { hints: ["A fruit.", "It is red"] },
    "an elephant": { hints: ["An animal.", "It is big."] },
    "ice cream": { hints: ["Edible.", "Sweet."] },
    "the Eiffel Tower": { hints: ["In Europe.", "It is tall"] },
    "a backpack": { hints: ["An object.", "Can be worn."] },
    "swimming": { hints: ["An activity.", "Related to water."] },
    "a shark": { hints: ["An animal.", "You usually find it in oceans."] },
    "pasta": { hints: ["A food.", "It is made from wheat flour."] },
    "Mickey Mouse": { hints: ["A fictional character."] },
    "a camera": { hints: ["An object."] },
    "cooking": { hints: ["An activity.", "You usually do it in at home."] },
    "an apple": { hints: ["Healthy", "It can be red."] },
    "a taco": { hints: ["A food."] },
    "London": { hints: ["A place."] },
    "orange juice": { hints: ["A beverage."] },
    "gravity": { hints: ["Cannot be touched", "It pulls objects toward each other."] },
    "a parrot": { hints: ["A bird."] },
    "a sandwich": { hints: ["A food."] },
    "Sherlock Holmes": { hints: ["A fictional character.", "He lived in London."] },
    "a flashlight": { hints: ["An object."] },
    "a wedding": { hints: ["An event."] },
    "a watermelon": { hints: ["A fruit.", "It is large.", "It is green."] },
    "popcorn": { hints: ["A food.", "Related to movies."] },
    "the Great Wall": { hints: ["A famous landmark.", "It is located in Asia."] },
    "milk": { hints: ["A beverage.", "It is white."] },
    "a sunrise": { hints: ["A natural event.", "It happens every morning."] },
    "broccoli": { hints: ["It is green."] },
    "a croissant": { hints: ["A food."] },
    "Peter Pan": { hints: ["A fictional character.", "Lives in Neverland."] },
    "candy": { hints: ["Sweet.", "It comes in many colors.", "Children love it."] },
    "hope": { hints: ["An emotion.", "It can help people stay positive."] },
    "a pineapple": { hints: ["A fruit.", "It is sweet."] },
    "gingerbread": { hints: ["A food.", "You usually make it during holidays."] },
    "Santa Claus": { hints: ["A legendary figure.", "Has a white beard"] },
    "Tokyo": { hints: ["A place.", "In Asia."] },
    "a dream": { hints: ["An experience.", "It happens at night."] },
    "gummy bears": { hints: ["They are candy."] },
    "champagne": { hints: ["A beverage.", "You usually use it during celebrations."] },
    "fireworks": { hints: ["They create colorful displays.", "You usually see them in the sky."] },
    "a mango": { hints: ["A fruit."] },
    "Pinocchio": { hints: ["A fictional character."] },
    "hot chocolate": { hints: ["A beverage.", "It is warm."] },
    "a tomato": { hints: ["It is a fruit.", "It is red.", "It is juicy"] },
    "the Statue of Liberty": { hints: ["It is located in the Americas."] },
    "a lollipop": { hints: ["It is candy."] },
    "a lion": { hints: ["An animal."] },
    "Rome": { hints: ["A place."] },
    "a cookie": { hints: ["It is usually round.", "It is usually sweet."] },
    "Aladdin": { hints: ["A fictional character."] },
    "tea": { hints: ["A beverage.", "It originated in China."] },
    "a potato": { hints: ["A vegetable."] },
    "the Pyramids": { hints: ["A famous landmark", "It is an ancient structure."] },
    "a cupcake": { hints: ["It is a baked good.", "You usually eat it at parties."] },
    "a butterfly": { hints: ["An insect.", "It has wings."] },
    "Sydney": { hints: ["A place."] },
    "a grape": { hints: ["A fruit.", "It can be purple."] },
    "Snow White": { hints: ["A fictional character."] },
    "soda": { hints: ["A beverage."] },
    "a cucumber": { hints: ["A vegetable.", "It is green."] },
    "the Taj Mahal": { hints: ["A famous landmark.", "It is located in India."] },
    "a donut": { hints: ["A baked good.", "It is ring-shaped."] },
    "a kangaroo": { hints: ["An animal."] },
    "Batman": { hints: ["A fictional character."] },
    "smoothie": { hints: ["A beverage.", "It is made by blending fruits.", "It is thick and healthy."] },
    "an onion": { hints: ["A vegetable.", "It has many layers."] },
    "Disney World": { hints: ["A place."] },
    "a brownie": { hints: ["A baked good."] },
    "a peacock": { hints: ["A bird."] },
    "Elsa": { hints: ["A fictional character."] },
    "a key": { hints: ["The word has 3 letters.", "It is made of metal."] }
};
