export const items: string[] = [
    "a dolphin",
    "pizza",
    "Albert Einstein",
    "a banana",
    "Christmas",
    "Paris",
    "sushi",
    "Cinderella",
    "a mirror",
    "coffee",
    "a penguin",
    "chocolate",
    "a carrot",
    "a compass",
    "Halloween",
    "New York",
    "a hamburger",
    "Harry Potter",
    "lemonade",
    "a strawberry",
    "an elephant",
    "ice cream",
    "the Eiffel Tower",
    "a backpack",
    "swimming",
    "a shark",
    "pasta",
    "Mickey Mouse",
    "a camera",
    "cooking",
    "an apple",
    "a taco",
    "London",
    "orange juice",
    "gravity",
    "a parrot",
    "a sandwich",
    "Sherlock Holmes",
    "a flashlight",
    "a wedding",
    "a watermelon",
    "popcorn",
    "the Great Wall",
    "milk",
    "a sunrise",
    "broccoli",
    "a croissant",
    "Peter Pan",
    "candy",
    "hope",
    "a pineapple",
    "gingerbread",
    "Santa Claus",
    "Tokyo",
    "a dream",
    "gummy bears",
    "champagne",
    "fireworks",
    "a mango",
    "Pinocchio",
    "hot chocolate",
    "a tomato",
    "the Statue of Liberty",
    "a lollipop",
    "a lion",
    "Rome",
    "a cookie",
    "Aladdin",
    "tea",
    "a potato",
    "the Pyramids",
    "a cupcake",
    "a butterfly",
    "Sydney",
    "a grape",
    "Snow White",
    "soda",
    "a cucumber",
    "the Taj Mahal",
    "a donut",
    "a kangaroo",
    "Batman",
    "smoothie",
    "an onion",
    "Disney World",
    "a brownie",
    "a peacock",
    "Elsa"
];

export const DEFAULT_ITEM = "a key";

export const itemDetails: { [key: string]: { hints: string[] } } = {
    "a dolphin": { hints: ["An animal.", "You usually find it in oceans."] },
    "pizza": { hints: ["It is a food.", "It is round", "The word has 5 letters."] },
    "Albert Einstein": { hints: ["A famous person.", "This person won the Nobel Prize"] },
    "a banana": { hints: ["A fruit.", "It is usually yellow"] },
    "Christmas": { hints: ["You cannot touch it"] },
    "Paris": { hints: ["A place."] },
    "sushi": { hints: ["It is a food.", "Related to Japan"]},
    "Cinderella": { hints: ["A fictional character"] },
    "a mirror": { hints: ["You usually find it in bedrooms."] },
    "coffee": { hints: ["A liquid", "Related to the morning"] },
    "a penguin": { hints: ["A bird that cannot fly.", "It has black and white coloring."] },
    "chocolate": { hints: ["A food.", "It is usually black"] },
    "a carrot": { hints: ["A vegetable.", "It is orange"] },
    "a compass": { hints: ["A tool."] },
    "Halloween": { hints: ["A day."] },
    "New York": { hints: ["A place."] },
    "a hamburger": { hints: ["A food."] },
    "Harry Potter": { hints: ["A fictional character.", "Related to lightning."] },
    "lemonade": { hints: ["A beverage.", "It is sour."] },
    "a strawberry": { hints: ["A fruit.", "It is red"] },
    "an elephant": { hints: ["An animal.", "It is big."] },
    "ice cream": { hints: ["Edible.", "Sweet."] },
    "the Eiffel Tower": { hints: ["In Europe.", "It is tall"] },
    "a backpack": { hints: ["An object.", "Can be worn."] },
    "swimming": { hints: ["An activity.", "Related to water."] },
    "a shark": { hints: ["An animal.", "You usually find it in oceans."] },
    "pasta": { hints: ["A food.", "It is made from wheat flour."] },
    "Mickey Mouse": { hints: ["A fictional character."] },
    "a camera": { hints: ["An object."] },
    "cooking": { hints: ["An activity.", "You usually do it in at home."] },
    "an apple": { hints: ["Healthy", "It can be red."] },
    "a taco": { hints: ["A food."] },
    "London": { hints: ["A place."] },
    "orange juice": { hints: ["A beverage."] },
    "gravity": { hints: ["Cannot be touched", "It pulls objects toward each other."] },
    "a parrot": { hints: ["A bird."] },
    "a sandwich": { hints: ["A food."] },
    "Sherlock Holmes": { hints: ["A fictional character.", "He lived in London."] },
    "a flashlight": { hints: ["An object."] },
    "a wedding": { hints: ["An event."] },
    "a watermelon": { hints: ["A fruit.", "It is large.", "It is green."] },
    "popcorn": { hints: ["A food.", "Related to movies."] },
    "the Great Wall": { hints: ["A famous landmark.", "It is located in Asia."] },
    "milk": { hints: ["A beverage.", "It is white."] },
    "a sunrise": { hints: ["A natural event.", "It happens every morning."] },
    "broccoli": { hints: ["It is green."] },
    "a croissant": { hints: ["A food."] },
    "Peter Pan": { hints: ["A fictional character.", "Lives in Neverland."] },
    "candy": { hints: ["Sweet.", "It comes in many colors.", "Children love it."] },
    "hope": { hints: ["An emotion.", "It can help people stay positive."] },
    "a pineapple": { hints: ["A fruit.", "It is sweet."] },
    "gingerbread": { hints: ["A food.", "You usually make it during holidays."] },
    "Santa Claus": { hints: ["A legendary figure.", "Has a white beard"] },
    "Tokyo": { hints: ["A place.", "In Asia."] },
    "a dream": { hints: ["An experience.", "It happens at night."] },
    "gummy bears": { hints: ["They are candy."] },
    "champagne": { hints: ["A beverage.", "You usually use it during celebrations."] },
    "fireworks": { hints: ["They create colorful displays.", "You usually see them in the sky."] },
    "a mango": { hints: ["A fruit."] },
    "Pinocchio": { hints: ["A fictional character."] },
    "hot chocolate": { hints: ["A beverage.", "It is warm."] },
    "a tomato": { hints: ["It is a fruit.", "It is red.", "It is juicy"] },
    "the Statue of Liberty": { hints: ["It is located in the Americas."] },
    "a lollipop": { hints: ["It is candy."] },
    "a lion": { hints: ["An animal."] },
    "Rome": { hints: ["A place."] },
    "a cookie": { hints: ["It is usually round.", "It is usually sweet."] },
    "Aladdin": { hints: ["A fictional character."] },
    "tea": { hints: ["A beverage.", "It originated in China."] },
    "a potato": { hints: ["A vegetable."] },
    "the Pyramids": { hints: ["A famous landmark", "It is an ancient structure."] },
    "a cupcake": { hints: ["It is a baked good.", "You usually eat it at parties."] },
    "a butterfly": { hints: ["An insect.", "It has wings."] },
    "Sydney": { hints: ["A place."] },
    "a grape": { hints: ["A fruit.", "It can be purple."] },
    "Snow White": { hints: ["A fictional character."] },
    "soda": { hints: ["A beverage."] },
    "a cucumber": { hints: ["A vegetable.", "It is green."] },
    "the Taj Mahal": { hints: ["A famous landmark.", "It is located in India."] },
    "a donut": { hints: ["A baked good.", "It is ring-shaped."] },
    "a kangaroo": { hints: ["An animal."] },
    "Batman": { hints: ["A fictional character."] },
    "smoothie": { hints: ["A beverage.", "It is made by blending fruits.", "It is thick and healthy."] },
    "an onion": { hints: ["A vegetable.", "It has many layers."] },
    "Disney World": { hints: ["A place."] },
    "a brownie": { hints: ["A baked good."] },
    "a peacock": { hints: ["A bird."] },
    "Elsa": { hints: ["A fictional character."] },
    "a key": { hints: ["The word has 3 letters.", "It is made of metal."] }
};
